# Generated by Django 4.0.1 on 2022-03-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_picture_profile_pict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pict',
            new_name='picture',
        ),
    ]
